from __future__ import annotations

from dataclasses import asdict, dataclass

@dataclass(frozen=True)
class Feature:
    id: str
    category: str
    name: str
    executor: str
    status: str
    safety: str

# Status AVAILABLE berarti feature memiliki executor/adapter yang dapat dipanggil.
# Ketersediaan executor tidak menjamin finding; hasil runtime memakai DETECTED,
# NOT DETECTED, SKIPPED, NOT TESTED, atau INCONCLUSIVE berdasarkan evidence.
BUG_BOUNTY = [
("BB-01","Enumerasi Subdomain","ct_subdomains","AVAILABLE"),("BB-02","DNS Enumeration","dns","AVAILABLE"),("BB-03","WHOIS Lookup","external_whois","AVAILABLE"),("BB-04","ASN Discovery","external_asn","AVAILABLE"),("BB-05","IP Discovery","dns","AVAILABLE"),("BB-06","Reverse DNS","reverse_dns","AVAILABLE"),("BB-07","Certificate Enumeration","tls","AVAILABLE"),("BB-08","Certificate Transparency","ct_subdomains","AVAILABLE"),("BB-09","Technology Fingerprinting","technology","AVAILABLE"),("BB-10","HTTP Header Analyzer","headers","AVAILABLE"),("BB-11","HTTP Status Mapper","status_mapper","AVAILABLE"),("BB-12","Directory Discovery","directory_wordlist","AVAILABLE"),("BB-13","Endpoint Discovery","endpoints","AVAILABLE"),("BB-14","robots.txt Analyzer","robots","AVAILABLE"),("BB-15","sitemap.xml Analyzer","sitemap","AVAILABLE"),("BB-16","JavaScript Endpoint Extraction","js_endpoints","AVAILABLE"),("BB-17","Parameter Discovery","parameters","AVAILABLE"),("BB-18","Security Header Audit","headers","AVAILABLE"),("BB-19","Cookie Security Audit","cookies","AVAILABLE"),("BB-20","CORS Analyzer","cors","AVAILABLE"),("BB-21","Reflected XSS Detector","safe_reflection","AVAILABLE"),("BB-22","Stored XSS Indicator","stored_xss_indicator","AVAILABLE"),("BB-23","SQL Injection Detection","sqli_safe","AVAILABLE"),("BB-24","NoSQL Injection Indicator","nosql_indicator","AVAILABLE"),("BB-25","SSTI Detection","ssti_safe","AVAILABLE"),("BB-26","Open Redirect Detection","open_redirect","AVAILABLE"),("BB-27","SSRF Indicator","ssrf_indicator","AVAILABLE"),("BB-28","LFI Indicator","lfi_indicator","AVAILABLE"),("BB-29","Path Traversal Detection","path_traversal","AVAILABLE"),("BB-30","IDOR Candidate Detection","idor_candidate","AVAILABLE"),("BB-31","API Endpoint Discovery","api_docs","AVAILABLE"),("BB-32","OpenAPI Analyzer","openapi","AVAILABLE"),("BB-33","GraphQL Analyzer","graphql","AVAILABLE"),("BB-34","API Authentication Analyzer","api_auth","AVAILABLE"),("BB-35","JWT Analyzer","jwt","AVAILABLE"),("BB-36","TCP Port Discovery","ports","AVAILABLE"),("BB-37","Service Detection","service_banner","AVAILABLE"),("BB-38","TLS Audit","tls","AVAILABLE"),("BB-39","HTTP/HTTPS Comparison","http_https","AVAILABLE"),("BB-40","Network Exposure Report","exposure_report","AVAILABLE"),("BB-41","Cloud Asset Fingerprinting","cloud","AVAILABLE"),("BB-42","Public Storage Indicator","storage","AVAILABLE"),("BB-43","Cloud Metadata Reference Detector","metadata","AVAILABLE"),("BB-44","Subdomain Takeover Indicator","takeover","AVAILABLE"),("BB-45","CDN/WAF Detection","technology","AVAILABLE"),("BB-46","Vulnerability Correlation Engine","correlation","AVAILABLE"),("BB-47","Risk Scoring","risk_score","AVAILABLE"),("BB-48","Finding Deduplication","dedup","AVAILABLE"),("BB-49","Evidence Collector","evidence","AVAILABLE"),("BB-50","Professional Report Generator","report","AVAILABLE"),
]
OSINT = [
("OS-01","Domain intelligence"),("OS-02","Subdomain intelligence"),("OS-03","WHOIS intelligence"),("OS-04","ASN intelligence"),("OS-05","IP intelligence"),("OS-06","Reverse DNS intelligence"),("OS-07","Certificate intelligence"),("OS-08","Email domain intelligence"),("OS-09","Username enumeration"),("OS-10","Public profile discovery"),("OS-11","GitHub repository intelligence"),("OS-12","GitHub organization intelligence"),("OS-13","Public code search"),("OS-14","Public secret indicator scanning"),("OS-15","Paste-site reference discovery"),("OS-16","Document metadata extraction"),("OS-17","PDF metadata analysis"),("OS-18","Image metadata analysis"),("OS-19","EXIF extraction"),("OS-20","URL intelligence"),("OS-21","Historical URL discovery"),("OS-22","Archived endpoint discovery"),("OS-23","Technology intelligence"),("OS-24","CMS detection"),("OS-25","JavaScript library detection"),("OS-26","WAF detection"),("OS-27","CDN detection"),("OS-28","Cloud provider detection"),("OS-29","Email pattern discovery"),("OS-30","Public contact discovery"),("OS-31","Organization intelligence"),("OS-32","Company domain mapping"),("OS-33","Brand/domain correlation"),("OS-34","Certificate relationship mapping"),("OS-35","IP relationship mapping"),("OS-36","Subdomain relationship graph"),("OS-37","URL relationship graph"),("OS-38","Asset relationship graph"),("OS-39","Public breach-reference detection"),("OS-40","Credential exposure indicator"),("OS-41","Repository secret indicator"),("OS-42","Configuration exposure indicator"),("OS-43","Backup-file indicator"),("OS-44","Debug endpoint discovery"),("OS-45","Public documentation discovery"),("OS-46","Swagger/OpenAPI discovery"),("OS-47","Security.txt discovery"),("OS-48","Robots intelligence"),("OS-49","Sitemap intelligence"),("OS-50","OSINT correlation engine"),
]
REVERSE = [("RE-01","File Type Detection"),("RE-02","Hash Calculator"),("RE-03","Strings Extraction"),("RE-04","Entropy Analysis"),("RE-05","Binary Header Analysis"),("RE-06","ELF Analysis"),("RE-07","PE Analysis"),("RE-08","Mach-O Analysis"),("RE-09","APK Metadata Analysis"),("RE-10","Android Manifest Analysis"),("RE-11","DEX Analysis"),("RE-12","Java Class Analysis"),("RE-13","Import Analysis"),("RE-14","Export Analysis"),("RE-15","Section Analysis"),("RE-16","Symbol Analysis"),("RE-17","Embedded URL Extraction"),("RE-18","Embedded IP Extraction"),("RE-19","Embedded Secret Indicator"),("RE-20","Static Risk Analysis")]

FEATURES=[Feature(i,"BUG_BOUNTY",n,e,s,"non-destructive") for i,n,e,s in BUG_BOUNTY]+[Feature(i,"OSINT",n,"passive_osint" if i in {"OS-01","OS-02","OS-07","OS-23","OS-28","OS-29","OS-47","OS-48","OS-49"} else "osint_static", "AVAILABLE", "passive-only") for i,n in OSINT]+[Feature(i,"REVERSE",n,"reverse_static_analysis" if i in {"RE-01","RE-02","RE-03","RE-04","RE-05","RE-13","RE-14","RE-16","RE-17","RE-18","RE-19","RE-20"} else "reverse_specialized", "AVAILABLE", "static-only") for i,n in REVERSE]

def catalog(category=None):
    return [asdict(x) for x in FEATURES if category is None or x.category.lower()==category.lower()]

def counts():
    return {cat:{"total":len([x for x in FEATURES if x.category==cat]),"available":len([x for x in FEATURES if x.category==cat and x.status=="AVAILABLE"]),"planned":len([x for x in FEATURES if x.category==cat and x.status=="PLANNED"])} for cat in {"BUG_BOUNTY","OSINT","REVERSE"}}
